### ISSUE TITLE
Issue getting value for useLedgerAfterSlot

### ISSUE THREAD

**Issue by mr-14** [Kirael12/Cardano-Audit-Coincashew#2]
I'm getting a "KO" on `useLedgerAfterSlot` even after setting it to `-1` on my block producer node.

Should the script on line `#276` be
```
USELEDGER_VALUE=$(grep -oP '"useLedgerAfterSlot": \K-?[0-9]+' $TOPOLOGY)
```
instead of 
```
USELEDGER_VALUE=$(grep -oP '"useLedgerAfterSlot": \K[0-9]+' $TOPOLOGY)
```

Great work by the way!

**Comment by Kirael12** [comment]
Hello,

That's weird, it works fine on my setup. 

Could you post your BP topology file (remove the IP/FQDN) please ?

**Comment by Kirael12** [comment]
Hello @mr-14 i did several tests and it serms to work.

Are you using the v6 ? 
Could you show me your topology file ?

**Comment by mr-14** [comment]
Here's my topology.json
```
{
  "localRoots": [
    {
      "accessPoints": [
	{
          "address": "192.168.1.202",
          "port": 6000
        }
      ],
      "advertise": false,
      "valency": 2
    }
  ],
  "publicRoots": [],
  "useLedgerAfterSlot": -1
}
```

**Comment by mr-14** [comment]
Honestly, I'm not an expert in shell script or grep, but if you try the following
```
echo '"foo": -1' | grep -oP '"foo": \K[0-9]+'
```
It does not print out anything. However, changing it to the following will give you -1
```
echo '"foo": -1' | grep -oP '"foo": \K-?[0-9]+'
```

**Comment by Kirael12** [comment]
Hello, 

I double checked. Actually the latest version (**v6**) is as follow :

If your node is detected as a BP, then (line 350) :

if grep -q '"useLedgerAfterSlot":' $TOPOLOGY; then
                        USELEDGER_VALUE=$(**grep -oP '"useLedgerAfterSlot": \K-?[0-9]+'** $TOPOLOGY)
                        if [ "$USELEDGER_VALUE" == "-1" ]; then
                            echo -e " [\e[1;32mOK\e[0m] useLedgerAfterSlot option set to -1 "
                        else 
                            echo -e " [\e[1;31mKO\e[0m] useLedgerAfterSlot should be set to -1 on your Block Producer"
                        fi



If your node is detected as Relay, then (line 542) : 

if grep -q '"useLedgerAfterSlot":' $TOPOLOGY; then
                            USELEDGER_VALUE=$(grep -oP '"**useLedgerAfterSlot": \K[0-9]+' $TOPOLOGY**)
                            if [ "$USELEDGER_VALUE" -ge 0 ]; then
                                echo -e " [\e[1;32mOK\e[0m] useLedgerAfterSlot is greater or equal to 0 "
                            else
                                echo -e " [\e[1;31mKO\e[0m] useLedgerAfterSlot must be set to 0 or more on your Relay"
                            fi


So i think you might no be using the latest version ? Or maybe your node is detected as Relay instead of a BP ?

Could you post the output of the script ?

**Comment by mr-14** [comment]
It's working as expected now. Thanks for the help!
